application: regex-golang
version: 1
runtime: go
api_version: go1
instance_class: F1
automatic_scaling:
    max_pending_latency: 1s
    max_concurrent_requests: 20

handlers:
- url: /assets
  static_dir: assets
  secure: always

- url: /.*
  script: _go_app
  secure: always
